import { Planet } from "types/planet";

export const mockData: Planet[] = [
  {
    waterSurfaceArea: 657.5353423963438,
    name: "Tatooine",
    climate: ["arid"],
    terrain: ["desert"],
    population: 200000,
    residents: 10,
    url: "http://swapi.dev/api/planets/1/",
  },
  {
    waterSurfaceArea: 31415.926535897932,
    name: "Alderaan",
    climate: ["temperate"],
    terrain: ["grasslands", "mountains"],
    population: 2000000000,
    residents: 3,
    url: "http://swapi.dev/api/planets/2/",
  },
  {
    waterSurfaceArea: 5127.079210658542,
    name: "Yavin IV",
    climate: ["temperate", "tropical"],
    terrain: ["jungle", "rainforests"],
    population: 1000,
    residents: 0,
    url: "http://swapi.dev/api/planets/3/",
  },
  {
    waterSurfaceArea: 45238.93421169302,
    name: "Hoth",
    climate: ["frozen"],
    terrain: ["tundra", "ice caves", "mountain ranges"],
    population: null,
    residents: 0,
    url: "http://swapi.dev/api/planets/4/",
  },
  {
    waterSurfaceArea: 4473.627938711866,
    name: "Dagobah",
    climate: ["murky"],
    terrain: ["swamp", "jungles"],
    population: null,
    residents: 0,
    url: "http://swapi.dev/api/planets/5/",
  },
  {
    waterSurfaceArea: 0,
    name: "Bespin",
    climate: ["temperate"],
    terrain: ["gas giant"],
    population: 6000000,
    residents: 1,
    url: "http://swapi.dev/api/planets/6/",
  },
  {
    waterSurfaceArea: 2463.008640414398,
    name: "Endor",
    climate: ["temperate"],
    terrain: ["forests", "mountains", "lakes"],
    population: 30000000,
    residents: 1,
    url: "http://swapi.dev/api/planets/7/",
  },
  {
    waterSurfaceArea: 9138.26471076199,
    name: "Naboo",
    climate: ["temperate"],
    terrain: ["grassy hills", "swamps", "forests", "mountains"],
    population: 4500000000,
    residents: 11,
    url: "http://swapi.dev/api/planets/8/",
  },
  {
    waterSurfaceArea: null,
    name: "Coruscant",
    climate: ["temperate"],
    terrain: ["cityscape", "mountains"],
    population: 1000000000000,
    residents: 3,
    url: "http://swapi.dev/api/planets/9/",
  },
  {
    waterSurfaceArea: 123904.41425758145,
    name: "Kamino",
    climate: ["temperate"],
    terrain: ["ocean"],
    population: 1000000000,
    residents: 3,
    url: "http://swapi.dev/api/planets/10/",
  },
  {
    waterSurfaceArea: 3571.990847131595,
    name: "Geonosis",
    climate: ["temperate", "arid"],
    terrain: ["rock", "desert", "mountain", "barren"],
    population: 100000000000,
    residents: 1,
    url: "http://swapi.dev/api/planets/11/",
  },
  {
    waterSurfaceArea: 729.47781416355,
    name: "Utapau",
    climate: ["temperate", "arid", "windy"],
    terrain: ["scrublands", "savanna", "canyons", "sinkholes"],
    population: 95000000,
    residents: 1,
    url: "http://swapi.dev/api/planets/12/",
  },
  {
    waterSurfaceArea: 0,
    name: "Mustafar",
    climate: ["hot"],
    terrain: ["volcanoes", "lava rivers", "mountains", "caves"],
    population: 20000,
    residents: 0,
    url: "http://swapi.dev/api/planets/13/",
  },
  {
    waterSurfaceArea: 48122.91626768845,
    name: "Kashyyyk",
    climate: ["tropical"],
    terrain: ["jungle", "forests", "lakes", "rivers"],
    population: 45000000,
    residents: 2,
    url: "http://swapi.dev/api/planets/14/",
  },
  {
    waterSurfaceArea: 0,
    name: "Polis Massa",
    climate: ["artificial temperate "],
    terrain: ["airless asteroid"],
    population: 1000000,
    residents: 0,
    url: "http://swapi.dev/api/planets/15/",
  },
  {
    waterSurfaceArea: null,
    name: "Mygeeto",
    climate: ["frigid"],
    terrain: ["glaciers", "mountains", "ice canyons"],
    population: 19000000,
    residents: 0,
    url: "http://swapi.dev/api/planets/16/",
  },
  {
    waterSurfaceArea: null,
    name: "Felucia",
    climate: ["hot", "humid"],
    terrain: ["fungus forests"],
    population: 8500000,
    residents: 0,
    url: "http://swapi.dev/api/planets/17/",
  },
  {
    waterSurfaceArea: null,
    name: "Cato Neimoidia",
    climate: ["temperate", "moist"],
    terrain: ["mountains", "fields", "forests", "rock arches"],
    population: 10000000,
    residents: 1,
    url: "http://swapi.dev/api/planets/18/",
  },
  {
    waterSurfaceArea: null,
    name: "Saleucami",
    climate: ["hot"],
    terrain: ["caves", "desert", "mountains", "volcanoes"],
    population: 1400000000,
    residents: 0,
    url: "http://swapi.dev/api/planets/19/",
  },
  {
    waterSurfaceArea: null,
    name: "Stewjon",
    climate: ["temperate"],
    terrain: ["grass"],
    population: null,
    residents: 1,
    url: "http://swapi.dev/api/planets/20/",
  },
  {
    waterSurfaceArea: null,
    name: "Eriadu",
    climate: ["polluted"],
    terrain: ["cityscape"],
    population: 22000000000,
    residents: 1,
    url: "http://swapi.dev/api/planets/21/",
  },
  {
    waterSurfaceArea: 48380.526865282816,
    name: "Corellia",
    climate: ["temperate"],
    terrain: ["plains", "urban", "hills", "forests"],
    population: 3000000000,
    residents: 2,
    url: "http://swapi.dev/api/planets/22/",
  },
  {
    waterSurfaceArea: 28459.05953033922,
    name: "Rodia",
    climate: ["hot"],
    terrain: ["jungles", "oceans", "urban", "swamps"],
    population: 1300000000,
    residents: 1,
    url: "http://swapi.dev/api/planets/23/",
  },
  {
    waterSurfaceArea: null,
    name: "Nal Hutta",
    climate: ["temperate"],
    terrain: ["urban", "oceans", "swamps", "bogs"],
    population: 7000000000,
    residents: 1,
    url: "http://swapi.dev/api/planets/24/",
  },
  {
    waterSurfaceArea: null,
    name: "Dantooine",
    climate: ["temperate"],
    terrain: ["oceans", "savannas", "mountains", "grasslands"],
    population: 1000,
    residents: 0,
    url: "http://swapi.dev/api/planets/25/",
  },
  {
    waterSurfaceArea: 39408.13824663037,
    name: "Bestine IV",
    climate: ["temperate"],
    terrain: ["rocky islands", "oceans"],
    population: 62000000,
    residents: 1,
    url: "http://swapi.dev/api/planets/26/",
  },
  {
    waterSurfaceArea: 8827.875356587318,
    name: "Ord Mantell",
    climate: ["temperate"],
    terrain: ["plains", "seas", "mesas"],
    population: 4000000000,
    residents: 0,
    url: "http://swapi.dev/api/planets/27/",
  },
  {
    waterSurfaceArea: null,
    name: null,
    climate: null,
    terrain: null,
    population: null,
    residents: 5,
    url: "http://swapi.dev/api/planets/28/",
  },
  {
    waterSurfaceArea: null,
    name: "Trandosha",
    climate: ["arid"],
    terrain: ["mountains", "seas", "grasslands", "deserts"],
    population: 42000000,
    residents: 1,
    url: "http://swapi.dev/api/planets/29/",
  },
  {
    waterSurfaceArea: null,
    name: "Socorro",
    climate: ["arid"],
    terrain: ["deserts", "mountains"],
    population: 300000000,
    residents: 1,
    url: "http://swapi.dev/api/planets/30/",
  },
  {
    waterSurfaceArea: 69303.53393819084,
    name: "Mon Cala",
    climate: ["temperate"],
    terrain: ["oceans", "reefs", "islands"],
    population: 27000000000,
    residents: 1,
    url: "http://swapi.dev/api/planets/31/",
  },
  {
    waterSurfaceArea: 33929.20065876977,
    name: "Chandrila",
    climate: ["temperate"],
    terrain: ["plains", "forests"],
    population: 1200000000,
    residents: 1,
    url: "http://swapi.dev/api/planets/32/",
  },
  {
    waterSurfaceArea: 4014.955411287756,
    name: "Sullust",
    climate: ["superheated"],
    terrain: ["mountains", "volcanoes", "rocky deserts"],
    population: 18500000000,
    residents: 1,
    url: "http://swapi.dev/api/planets/33/",
  },
  {
    waterSurfaceArea: null,
    name: "Toydaria",
    climate: ["temperate"],
    terrain: ["swamps", "lakes"],
    population: 11000000,
    residents: 1,
    url: "http://swapi.dev/api/planets/34/",
  },
  {
    waterSurfaceArea: null,
    name: "Malastare",
    climate: ["arid", "temperate", "tropical"],
    terrain: ["swamps", "deserts", "jungles", "mountains"],
    population: 2000000000,
    residents: 1,
    url: "http://swapi.dev/api/planets/35/",
  },
  {
    waterSurfaceArea: null,
    name: "Dathomir",
    climate: ["temperate"],
    terrain: ["forests", "deserts", "savannas"],
    population: 5200,
    residents: 1,
    url: "http://swapi.dev/api/planets/36/",
  },
  {
    waterSurfaceArea: 3330.0882128051812,
    name: "Ryloth",
    climate: ["temperate", "arid", "subartic"],
    terrain: ["mountains", "valleys", "deserts", "tundra"],
    population: 1500000000,
    residents: 2,
    url: "http://swapi.dev/api/planets/37/",
  },
  {
    waterSurfaceArea: null,
    name: "Aleen Minor",
    climate: null,
    terrain: null,
    population: null,
    residents: 1,
    url: "http://swapi.dev/api/planets/38/",
  },
  {
    waterSurfaceArea: null,
    name: "Vulpter",
    climate: ["temperate", "artic"],
    terrain: ["urban", "barren"],
    population: 421000000,
    residents: 1,
    url: "http://swapi.dev/api/planets/39/",
  },
  {
    waterSurfaceArea: null,
    name: "Troiken",
    climate: null,
    terrain: ["desert", "tundra", "rainforests", "mountains"],
    population: null,
    residents: 1,
    url: "http://swapi.dev/api/planets/40/",
  },
  {
    waterSurfaceArea: null,
    name: "Tund",
    climate: null,
    terrain: ["barren", "ash"],
    population: 0,
    residents: 1,
    url: "http://swapi.dev/api/planets/41/",
  },
  {
    waterSurfaceArea: null,
    name: "Haruun Kal",
    climate: ["temperate"],
    terrain: ["toxic cloudsea", "plateaus", "volcanoes"],
    population: 705300,
    residents: 1,
    url: "http://swapi.dev/api/planets/42/",
  },
  {
    waterSurfaceArea: 0,
    name: "Cerea",
    climate: ["temperate"],
    terrain: ["verdant"],
    population: 450000000,
    residents: 1,
    url: "http://swapi.dev/api/planets/43/",
  },
  {
    waterSurfaceArea: 78414.15263360125,
    name: "Glee Anselm",
    climate: ["tropical", "temperate"],
    terrain: ["lakes", "islands", "swamps", "seas"],
    population: 500000000,
    residents: 1,
    url: "http://swapi.dev/api/planets/44/",
  },
  {
    waterSurfaceArea: null,
    name: "Iridonia",
    climate: null,
    terrain: ["rocky canyons", "acid pools"],
    population: null,
    residents: 1,
    url: "http://swapi.dev/api/planets/45/",
  },
  {
    waterSurfaceArea: null,
    name: "Tholoth",
    climate: null,
    terrain: null,
    population: null,
    residents: 0,
    url: "http://swapi.dev/api/planets/46/",
  },
  {
    waterSurfaceArea: null,
    name: "Iktotch",
    climate: ["arid", "rocky", "windy"],
    terrain: ["rocky"],
    population: null,
    residents: 1,
    url: "http://swapi.dev/api/planets/47/",
  },
  {
    waterSurfaceArea: null,
    name: "Quermia",
    climate: null,
    terrain: null,
    population: null,
    residents: 1,
    url: "http://swapi.dev/api/planets/48/",
  },
  {
    waterSurfaceArea: null,
    name: "Dorin",
    climate: ["temperate"],
    terrain: null,
    population: null,
    residents: 1,
    url: "http://swapi.dev/api/planets/49/",
  },
  {
    waterSurfaceArea: null,
    name: "Champala",
    climate: ["temperate"],
    terrain: ["oceans", "rainforests", "plateaus"],
    population: 3500000000,
    residents: 1,
    url: "http://swapi.dev/api/planets/50/",
  },
  {
    waterSurfaceArea: null,
    name: "Mirial",
    climate: null,
    terrain: ["deserts"],
    population: null,
    residents: 2,
    url: "http://swapi.dev/api/planets/51/",
  },
  {
    waterSurfaceArea: null,
    name: "Serenno",
    climate: null,
    terrain: ["rainforests", "rivers", "mountains"],
    population: null,
    residents: 1,
    url: "http://swapi.dev/api/planets/52/",
  },
  {
    waterSurfaceArea: null,
    name: "Concord Dawn",
    climate: null,
    terrain: ["jungles", "forests", "deserts"],
    population: null,
    residents: 1,
    url: "http://swapi.dev/api/planets/53/",
  },
  {
    waterSurfaceArea: null,
    name: "Zolan",
    climate: null,
    terrain: null,
    population: null,
    residents: 1,
    url: "http://swapi.dev/api/planets/54/",
  },
  {
    waterSurfaceArea: 0,
    name: "Ojom",
    climate: ["frigid"],
    terrain: ["oceans", "glaciers"],
    population: 500000000,
    residents: 1,
    url: "http://swapi.dev/api/planets/55/",
  },
  {
    waterSurfaceArea: null,
    name: "Skako",
    climate: ["temperate"],
    terrain: ["urban", "vines"],
    population: 500000000000,
    residents: 1,
    url: "http://swapi.dev/api/planets/56/",
  },
  {
    waterSurfaceArea: 21676.98930976957,
    name: "Muunilinst",
    climate: ["temperate"],
    terrain: ["plains", "forests", "hills", "mountains"],
    population: 5000000000,
    residents: 1,
    url: "http://swapi.dev/api/planets/57/",
  },
  {
    waterSurfaceArea: null,
    name: "Shili",
    climate: ["temperate"],
    terrain: ["cities", "savannahs", "seas", "plains"],
    population: null,
    residents: 1,
    url: "http://swapi.dev/api/planets/58/",
  },
  {
    waterSurfaceArea: null,
    name: "Kalee",
    climate: ["arid", "temperate", "tropical"],
    terrain: ["rainforests", "cliffs", "canyons", "seas"],
    population: 4000000000,
    residents: 1,
    url: "http://swapi.dev/api/planets/59/",
  },
  {
    waterSurfaceArea: null,
    name: "Umbara",
    climate: null,
    terrain: null,
    population: null,
    residents: 1,
    url: "http://swapi.dev/api/planets/60/",
  },
];
